/** @type {import('next').NextConfig} */

// This is a 100% client-side static app. No backend, no server functions.
// Output is generated by `next build` and can be hosted on any static
// provider (Vercel, Netlify, GitHub Pages, etc.).
//
// Security headers (CSP, X-Frame-Options, etc.) are configured in
// vercel.json — Next.js `headers()` does not run when output: export.
const nextConfig = {
  output: "export",
  images: { unoptimized: true },
  trailingSlash: true,
};

module.exports = nextConfig;
